version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    
  evc.crowdlanding.api:
    image: ${DOCKER_REGISTRY-}evccrowdlandingapi
    build:
      context: .
      dockerfile: EVC.CrowdLanding.Api/Dockerfile
    depends_on:
      - sql.data

  evc.crowdlanding.client:
    image: ${DOCKER_REGISTRY-}evccrowdlandingclient
    build:
      context: .
      dockerfile: EVC.CrowdLanding.Client/Dockerfile
   
