// <auto-generated />
using System;
using EVC.CrowdLanding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EVC.CrowdLanding.Api.Migrations
{
    [DbContext(typeof(CrowdFundingsDbContext))]
    [Migration("20190202152512_ModifiedUser")]
    partial class ModifiedUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EVC.CrowdLanding.DomainModel.Funding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("InvestmentCompany");

                    b.Property<bool>("IsInvestmentRequired");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("TypeOfInvestment");

                    b.HasKey("Id");

                    b.ToTable("Fundings");
                });

            modelBuilder.Entity("EVC.CrowdLanding.DomainModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EVC.CrowdLanding.DomainModel.UsersFundings", b =>
                {
                    b.Property<int>("FundingId");

                    b.Property<int>("UserId");

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("TimeOfFunding");

                    b.HasKey("FundingId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersFundings");
                });

            modelBuilder.Entity("EVC.CrowdLanding.DomainModel.UsersFundings", b =>
                {
                    b.HasOne("EVC.CrowdLanding.DomainModel.Funding", "Funding")
                        .WithMany("UsersFundings")
                        .HasForeignKey("FundingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EVC.CrowdLanding.DomainModel.User", "User")
                        .WithMany("UsersFundings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
